name: Release

on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  Release:
    uses: gesslar/Maint/.github/workflows/ReleaseMuddyInjectMupdate.yaml@main
    secrets: inherit
    permissions:
      contents: write
